### ISSUE TITLE
Panic exception when quantizing with more centroids than instances

### ISSUE THREAD

**Issue by danieldk** [danieldk/snakefusion#6]
```
snakefusion/tests/test_quantization.py:2: PanicException
----------------------------------------- Captured stderr call -----------------------------------------
thread 'thread '<unnamed>' panicked at 'Cannot pick more centroids than instances: 43 instances, 256 centroids', /Users/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/reductive-0.8.0/src/kmeans.rs:62:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Cannot pick more centroids than instances: 43 instances, 256 centroids', /Users/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/reductive-0.8.0/src/kmeans.rs:62:9thread '<unnamed>' panicked at 'Cannot pick more centroids than instances: 43 instances, 256 centroids', /Users/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/reductive-0.8.0/src/kmeans.rs:62:9
thread '<unnamed>' panicked at 'Cannot pick more centroids than instances: 43 instances, 256 centroids', /Users/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/reductive-0.8.0/src/kmeans.rs:62:9
<unnamed>' panicked at 'Cannot pick more centroids than instances: 43 instances, 256 centroids', /Users/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/reductive-0.8.0/src/kmeans.rs:62:9
```

**Comment by danieldk** [comment]
Fixed by #10 .
